### ISSUE TITLE
What about GPS support and question about MQTT..

### ISSUE THREAD

**Issue by itProfi** [JohnHJ01/A7_GPRS#1]
Good day! Thank you for your libraries for A7 GPRS modem..I have some question:
1. Do you plan add GPS command?
2. What the library MQTT.h you used in you repository?
Thank you!

**Comment by haojie-chan** [comment]
Hi. This code is created for my school project, and I am adding GPS into the code now.

For MQTT, I abandoned MQTT in favour of HTTP. I was trying to implement MQTT client in Arduino, using PAHO library, but for some reason, I failed. I don't know is it because of my library or module. But HTTP works wonderfully, thus I shifted my focus.

**Comment by itProfi** [comment]
Ok, thank for you answer!
